databases:
  - name: DB_to_yama
    databaseName: db_to_yama
    user: db_to_yama_user
    region: singapore

services:
  - type: web
    name: to_yama
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    ruby_version: 3.1.2
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DB_to_yama
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

